project:
  type: book
  output-dir: docs

book:
  title: "Multilevel Multilingual"
  author: "Andrew Grogan-Kaylor"
  date: "today"
  sharing: [twitter, facebook, linkedin]
  site-url: https://agrogan1.github.io/multilevel-multilingual/
  search: true
  repo-url: https://github.com/agrogan1/multilevel-multilingual
  repo-actions: [issue]
  chapters:
    - index.qmd
    - cross-classified-multilingual.qmd
  navbar:
    background: primary
      
google-scholar: true

format:
  html:
    theme: 
      light: simplex
      dark: vapor
    css: multilevel-multilingual.css
    toc: true
    execute:
      echo: false
      warning: false
      freeze: auto



