project:
  type: book
  output-dir: docs

book:
  title: "Multilevel Multilingual"
  subtitle: "Multilevel Models in Stata, R and Julia"
  author: "Andrew Grogan-Kaylor"
  date: "today"
  cover-image: multilevel-multilingual.png
  sharing: [twitter, facebook, linkedin]
  site-url: https://agrogan1.github.io/multilevel-multilingual/
  search: true
  repo-url: https://github.com/agrogan1/multilevel-multilingual
  repo-actions: [issue]
  downloads: [pdf]
  twitter-card: true
  open-graph: true
  chapters:
    - index.qmd
    - cross-classified-multilingual.qmd
  navbar:
    background: primary
      
google-scholar: true

format:
  html:
    theme: 
      light: cosmo
      dark: vapor
    css: multilevel-multilingual.css
    toc: true
    execute:
      echo: true
      warning: false
      freeze: auto
  pdf:
    lot: true
    lof: true
    keep-tex: true
    execute:
      echo: true
      warning: false   
      freeze: auto


