project:
  type: book
  output-dir: docs

book:
  title: "Multilevel Multilingual"
  subtitle: "Multilevel Models in Stata, R and Julia"
  author: "Andrew Grogan-Kaylor"
  date: "today"
  cover-image: multilevel-multilingual.png
  sharing: [twitter, facebook, linkedin]
  site-url: https://agrogan1.github.io/multilevel-multilingual/
  search: true
  repo-url: https://github.com/agrogan1/multilevel-multilingual
  repo-actions: [issue]
  downloads: [pdf]
  twitter-card: true
  open-graph: true
  chapters:
    - index.qmd
    - workflows-multilingual.qmd
    - storage-multilingual.qmd
    - descriptives-multilingual.qmd
    - unconditional-multilingual.qmd
    - cross-sectional-multilingual.qmd
    - longitudinal-multilingual.qmd
    - logistic-multilingual.qmd
    - morelevels-multilingual.qmd
    - reshape-multilingual.qmd
    - aggregating-multilingual.qmd
    - references.qmd
  navbar:
    background: primary

bibliography: multilevel-multilingual.bib

csl: apa.csl
      
google-scholar: true

format:
  html:
    theme: 
      light: default
      dark: vapor
    css: multilevel-multilingual.css
    lightbox: true
    embed-resources: false
    toc: true
    execute:
      echo: true
      warning: false
      freeze: auto
  pdf:
    lot: true
    keep-tex: true
    fig-width: 6
    execute:
      echo: true
      warning: false   
      freeze: auto
  docx:
    reference-doc: markstat.docx
    fig-dpi: 600
    execute:
      echo: true
      warning: false
      freeze: auto


      
