# Models With Three or More Levels and Cross-Classified Models

```{r}
#| label: morelevelssetup
#| echo: false
#| output: false

library(Statamarkdown)

library(lme4) 

library(JuliaCall)

julia_setup(JULIA_HOME = "/Applications/Julia-1.10.app/Contents/Resources/julia/bin")

```

## Introduction

A two level multilevel model imagines that *Level 1* units are nested in *Level 2* units. A three level multilevel model imagines that *Level 1* units are nested in *Level 2* units, which are in turn nested in *Level 3*. 

A *cross-classified* model imagines that the nesting is not hierarchical, but rather that there are two sets of clusters or nestings in which individuals may be nested. 

Below, I describe the use of [Stata](https://www.stata.com/), [R](https://www.r-project.org/), and [Julia](https://www.julialang.org/) to estimate these models.

## Three Or More Levels {#sec-fourlevel}

### The Data
### The Equation

## Cross-Classified Models

### The Data

### The Equation

### Run The Models

::: {.panel-tabset group="language"}

#### Stata

#### R

#### Julia

:::

### Interpretation

## Cross-Classified Models

### The Data

### The Equation

### Run The Models

::: {.panel-tabset group="language"}

#### Stata

#### R

#### Julia

:::

### Interpretation

