graph LR

subgraph project 1
    project1-->syntax1[syntax]
    project1-->data1[data]
    project1-->graphs1[graphs]
    project1-->output1[output]
    project1-->writeup1[writeup]
    end

subgraph project 2
    project2-->syntax2[syntax]
    project2-->data2[data]
    project2-->graphs2[graphs]
    project2-->output2[output]
    project2-->writeup2[writeup]
    end

subgraph project 3
    project3-->syntax3[syntax]
    project3-->data3[data]
    project3-->graphs3[graphs]
    project3-->output3[output]
    project3-->writeup3[writeup]
    end
