# Unconditional Model

## The Equation

$$\text{outcome}_{ij}= \beta_0 + u_{0j} + e_{ij}$$ {#eq-MLMunconditional}


The Intraclass Correlation Coefficient (ICC) is given by:

$$\text{ICC} = \frac{var(u_{0j})}{var(u_{0j}) + var(e_{ij})}$$ {#eq-ICCunconditional}

```{r}
#| label: unconditionalsetup
#| echo: false
#| output: false

library(Statamarkdown)

library(lme4) 

library(JuliaCall)

julia_setup(JULIA_HOME = "/Applications/Julia-1.8.app/Contents/Resources/julia/bin")

```

## Run Models

::: {.panel-tabset group="language"}

### Stata

```{stata, collectcode=TRUE}

use simulated_multilevel_data.dta // use data

```

```{stata, collectcode=TRUE}

mixed outcome || country: // unconditional model
  
```

```{stata}
  
estat icc // calculate icc

```

### R

```{r}

library(haven)

df <- read_dta("simulated_multilevel_data.dta")

```

```{r}
#| warning: false

fit0 <- lmer(outcome ~ (1 | country),
             data = df)

summary(fit0)

```

```{r}

library(performance)

performance::icc(fit0) # calculate icc

```

### Julia

```{julia}
#| output: false

using Tables, MixedModels, MixedModelsExtras, StatFiles, DataFrames, CategoricalArrays, DataFramesMeta

df = DataFrame(load("simulated_multilevel_data.dta"))

```

```{julia}

@transform!(df, :country = categorical(:country))

```

```{julia}

m0 = fit(MixedModel, @formula(outcome ~ (1 + warmth | country)), df)

```

```{julia}

icc(m0)

```



:::
